const fs=require('fs');
const path=require('path');
const vm=require('vm');
const assert=require('assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../firebase-costos-sync-original.js'),'utf8');
const start=source.indexOf('  function mergeAppCatalog(');
const end=source.indexOf('\n  function installStyles()',start);
const context=vm.createContext({clone:value=>JSON.parse(JSON.stringify(value))});
vm.runInContext(source.slice(start,end),context);
const remote={products:[{id:'cheese',name:'Cheesecake',recipe:[{ingredientId:'crema',qty:50},{ingredientId:'queso',qty:50}]}],ingredients:[{id:'crema',purchasePrice:7250}],weeks:[{id:'closed',orders:[{qty:3}]}]};
const stale={products:[{id:'cheese',name:'Cheesecake',recipe:[{ingredientId:'vaso',qty:1}]}],ingredients:[{id:'crema',purchasePrice:0}],weeks:[]};
assert.deepEqual(context.mergeAppCatalog(stale,remote),remote);
assert.deepEqual(context.mergeAppCatalog(null,remote),remote);
assert.deepEqual(context.mergeAppCatalog(remote,null),remote);
assert.equal(context.mergeAppCatalog(null,null),null);
const result=context.mergeAppCatalog(stale,remote);result.products[0].recipe=[];
assert.equal(remote.products[0].recipe.length,2);
assert.equal(stale.products[0].recipe.length,1);
console.log('PASS: opening costs preserves remote recipes, prices, sales; initial offline state and source objects remain intact.');
